AllCops:
  Include:
    - "**/*.rb"
    - "**/*.jbuilder"
    - "**/*.ruby"
    - "**/*.ru"
    - "**/*.spec"
    - "**/Gemfile"
    - "**/Rakefile"
  Exclude:
    - "node_modules/**/*"
    - ".git/**/*"
    - "bin/**"
  StyleGuideBaseURL: https://rubystyle.guide
  NewCops: enable

require: rubocop-rails

Rails:
  StyleGuideBaseURL: https://rails.rubystyle.guide

Metrics/MethodLength:
  Enabled: false
