# frozen_string_literal: true

# Migration class generated by Rails
class CreateTutorials < ActiveRecord::Migration[6.0]
  def change
    create_table :tutorials do |t|
      t.string :title
      t.string :description

      t.timestamps
    end
  end
end
